# https://hub.docker.com/_/mysql
version: '3.6'
services:

  mariadbm:
    image: mariadb:10.3
    #container_name: mysqldbm
    # build: .
    restart: always
    env_file:
      - .env
    # environment:
      # MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test
    ports:
      - "6113:3306"
    volumes:
      - ../../datasys/maria392dbm/:/var/lib/mysql/   # folder for mysql's internal data files.
      - .:/root                                   # folder for scripts, etc.
      - ../../data/maria392dbm/:/home                   # folder for exported data, etc.
    networks:
      - sister 
    # https://medium.freecodecamp.org/how-to-setup-log-rotation-for-a-docker-container-a508093912b2
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"
              

# https://docs.docker.com/compose/compose-file/#external-1   
networks:
  
  sister:
    name: sister
      external:true
      #I tried lining up external under name and got:
      # albe@pmdsdata4:/srv/dkr/392dkr/backend392$ make myrup
      # docker-compose  up --build  --force-recreate
      # ERROR: yaml.scanner.ScannerError: while scanning a simple key
        # in "./docker-compose.yml", line 33, column 5
      # could not find expected ':'
        # in "./docker-compose.yml", line 35, column 3
      # make: *** [myrup] Error 1
      

  # net2:
    # external:
      # name: netw2  
  # albe@pmdsdata4:/srv/dkr/392dkr/backend392$ make myrup
  # docker-compose  up --build  --force-recreate
  # WARNING: Some networks were defined but are not used by any service: net2
  # ERROR: Service "dbm" uses an undefined network "netw2"
  # make: *** [myrup] Error 1
      
  # network:
    # external: true
    # name: mynet3      
    # albe@pmdsdata4:/srv/dkr/392dkr/backend392$ make myrup
    # docker-compose  up --build  --force-recreate
    # WARNING: Some networks were defined but are not used by any service: network3
    # ERROR: Service "dbm" uses an undefined network "mynet3"
    # make: *** [myrup] Error 1
    