version: '3.6'

services:

  dbm:
    image: mysql:5.7.22
    # build: .
    restart: always
    # container_name: mysqlm
    env_file:
      - .env
    # environment:
      # MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test
    ports:
      - "6112:3306"
    volumes:
      # - /var/aa/mysql/:/var/lib/mysql/
      # - /var/www/mysql385/:/var/lib/mysql/
      - ../data/mysql392dbm/:/var/lib/mysql/   # folder for mysql's internal data files.
      - .:/root                                   # folder for scripts, etc.
      - ../data/data392/:/home                 # folder for exported data, etc.
    networks:
      - sister
      


# https://docs.docker.com/compose/compose-file/#external-1   
networks:
  
  sister:
    name: sister
      external:true
      #I tried lining up external under name and got:
      # albe@pmdsdata4:/srv/dkr/392dkr/backend392$ make myrup
      # docker-compose  up --build  --force-recreate
      # ERROR: yaml.scanner.ScannerError: while scanning a simple key
        # in "./docker-compose.yml", line 33, column 5
      # could not find expected ':'
        # in "./docker-compose.yml", line 35, column 3
      # make: *** [myrup] Error 1
      

  # net2:
    # external:
      # name: netw2  
  # albe@pmdsdata4:/srv/dkr/392dkr/backend392$ make myrup
  # docker-compose  up --build  --force-recreate
  # WARNING: Some networks were defined but are not used by any service: net2
  # ERROR: Service "dbm" uses an undefined network "netw2"
  # make: *** [myrup] Error 1
      
  # network:
    # external: true
    # name: mynet3      
    # albe@pmdsdata4:/srv/dkr/392dkr/backend392$ make myrup
    # docker-compose  up --build  --force-recreate
    # WARNING: Some networks were defined but are not used by any service: network3
    # ERROR: Service "dbm" uses an undefined network "mynet3"
    # make: *** [myrup] Error 1
    